# Python 上传脚本配置文件

# --- 路径设置 ---
# 请在这里为每个条目提供完整的绝对路径

    #上传视频稿件
#
    #:param List[str] video_path: 视频文件路径
    #:param str cookie_file: cookie文件路径
    #:param str title: 视频标题
    #:param int tid: 投稿分区
    #:param str tag: 视频标签, 英文逗号分隔多个tag
    #:param int copyright: 是否转载, 1-自制 2-转载
    #:param str source: 转载来源
    #:param str desc: 视频简介
    #:param str dynamic: 空间动态
    #:param str cover: 视频封面
    #:param int dolby: 是否开启杜比音效, 0-关闭 1-开启
    #:param int lossless_music: 是否开启Hi-Res, 0-关闭 1-开启
    #:param int no_reprint: 是否禁止转载, 0-允许 1-禁止
    #:param int open_elec: 是否开启充电, 0-关闭 1-开启
    #:param bool up_close_reply: 是否禁止评论, false-关闭 true-开启
    #:param bool up_selection_reply: 是否精选评论, false-关闭 true-开启
    #:param bool up_close_danmu: 是否禁止弹幕, false-关闭 true-开启
    #:param int limit: 单视频文件最大并发数
    #:param List[Credit] desc_v2: 视频简介v2
    #:param Optional[dtime] int dtime: 定时发布时间, 距离提交大于2小时小于15天, 格式为10位时间戳
    #:param Optional[UploadLine] line: 上传线路
    #:param Optional[ExtraFields] line: 上传额外参数
    #:param Optional[str] proxy: 代理
    
upload:
  tid: 17
  tag: "游戏,单机游戏,直播回放"
  copyright: 2 # 是否转载, 1-自制 2-转载
  source: "https://live.douyin.com/439720548986"
  desc: "直播回放为自动化录制上传 如有侵权 请联系删除"
  limit: 3 
  only_self: false  # 或 false 是否仅自己可见
  up_close_reply: false  # 是否禁止评论
  up_selection_reply: false  # 是否精选评论
  up_close_danmu: false  # 是否禁止弹幕

paths:
  # 视频文件所在的文件夹路径
  video_folder: "C:/Users/zhang/Desktop/DouyinLiveRecorder_v4.0.3/downloads/抖音直播/Jiaozi"


  # Cookies 文件的完整路径
  cookies_file: "C:/Users/zhang/Desktop/biliupR-v0.2.4-x86_64-windows/cookies.json"

  # 日志文件的完整路径
  log_file: "C:/Users/zhang/Desktop/bili/upload.log"
  log_file1: "C:/Users/zhang/Desktop/bili/upload1.log"

  # 在这里添加录制软件的完整路径
  recorder_exe_path: "C:/Users/zhang/Desktop/DouyinLiveRecorder_v4.0.3/DouyinLiveRecorder.exe"

  # 名字
  name: "小枫灬游戏解说"
  # run地址
  run_path: "C:/Users/zhang/Desktop/bili/up.exe"

# --- 录制软件设置 ---
recorder:
  # 在这里指定录制软件的进程名
  process_name: "DouyinLiveRecorder.exe"

# --- 脚本行为设置 ---
behavior:
  # 上传成功后是否删除本地文件 (true / false)
  delete_after_upload: true